data = read.table(file = "C:/Users/pejakalabhargava/Desktop/d-c4hw2.csv", header=T, sep=",")
data = data[,-c(3)]
result  = myKMeans(data,8)
SSE = result$SSE;
clusteringSSE = colSums(SSE)
result = result$result
x1 = min(data[,1])
x2 = max(data[,1])
y1 = min(data[,2])
y2 = max(data[,2])
du.cl1 = subset(result, result$clusters == 1)
du.cl2 = subset(result, result$clusters == 2)
du.cl3 = subset(result, result$clusters == 3)
du.cl4 = subset(result, result$clusters == 4)
du.cl5 = subset(result, result$clusters == 5)
du.cl6 = subset(result, result$clusters == 6)
du.cl7 = subset(result, result$clusters == 7)
du.cl8 = subset(result, result$clusters == 8)
title= paste("Cluster Distributions for k=8 with clustering SSE", clusteringSSE, sep="=")
plot(0, col=c(1), main = title,xlim=c(x1,x2), ylim=c(y1,y2),sub="bkakran", xlab = "length", ylab = "width")
grid()
i=1
points(du.cl1, col=c(i+1), pch=c(2+i))
points(du.cl2, col=c(i+2), pch=c(3+i))
points(du.cl3, col=c(i+3), pch=c(4+i))
points(du.cl4, col=c(i+4), pch=c(5+i))
points(du.cl5, col=c(i+5), pch=c(6+i))
points(du.cl6, col=c(i+6), pch=c(7+i))
points(du.cl7, col=c(i+7), pch=c(8+i))
points(du.cl8, col=c(i+8), pch=c(9+i))